/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IssueCreateNestedManyWithoutProjectsInput } from "./IssueCreateNestedManyWithoutProjectsInput";
import { Type } from "class-transformer";
import { ProjectMemberCreateNestedManyWithoutProjectsInput } from "./ProjectMemberCreateNestedManyWithoutProjectsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  createdBy?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => IssueCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => IssueCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => IssueCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  issues?: IssueCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectMemberCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ProjectMemberCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ProjectMemberCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  projectMembers?: ProjectMemberCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ProjectCreateInput as ProjectCreateInput };
