/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IssueUpdateManyWithoutProjectsInput } from "./IssueUpdateManyWithoutProjectsInput";
import { Type } from "class-transformer";
import { ProjectMemberUpdateManyWithoutProjectsInput } from "./ProjectMemberUpdateManyWithoutProjectsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  createdBy?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => IssueUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => IssueUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => IssueUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  issues?: IssueUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectMemberUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ProjectMemberUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ProjectMemberUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  projectMembers?: ProjectMemberUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ProjectUpdateInput as ProjectUpdateInput };
