/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { IssueLabelService } from "../issueLabel.service";
import { IssueLabelCreateInput } from "./IssueLabelCreateInput";
import { IssueLabel } from "./IssueLabel";
import { IssueLabelFindManyArgs } from "./IssueLabelFindManyArgs";
import { IssueLabelWhereUniqueInput } from "./IssueLabelWhereUniqueInput";
import { IssueLabelUpdateInput } from "./IssueLabelUpdateInput";

export class IssueLabelControllerBase {
  constructor(protected readonly service: IssueLabelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IssueLabel })
  async createIssueLabel(
    @common.Body() data: IssueLabelCreateInput
  ): Promise<IssueLabel> {
    return await this.service.createIssueLabel({
      data: {
        ...data,

        issue: data.issue
          ? {
              connect: data.issue,
            }
          : undefined,

        label: data.label
          ? {
              connect: data.label,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        issue: {
          select: {
            id: true,
          },
        },

        label: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [IssueLabel] })
  @ApiNestedQuery(IssueLabelFindManyArgs)
  async issueLabels(@common.Req() request: Request): Promise<IssueLabel[]> {
    const args = plainToClass(IssueLabelFindManyArgs, request.query);
    return this.service.issueLabels({
      ...args,
      select: {
        createdAt: true,
        id: true,

        issue: {
          select: {
            id: true,
          },
        },

        label: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IssueLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async issueLabel(
    @common.Param() params: IssueLabelWhereUniqueInput
  ): Promise<IssueLabel | null> {
    const result = await this.service.issueLabel({
      where: params,
      select: {
        createdAt: true,
        id: true,

        issue: {
          select: {
            id: true,
          },
        },

        label: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IssueLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateIssueLabel(
    @common.Param() params: IssueLabelWhereUniqueInput,
    @common.Body() data: IssueLabelUpdateInput
  ): Promise<IssueLabel | null> {
    try {
      return await this.service.updateIssueLabel({
        where: params,
        data: {
          ...data,

          issue: data.issue
            ? {
                connect: data.issue,
              }
            : undefined,

          label: data.label
            ? {
                connect: data.label,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          issue: {
            select: {
              id: true,
            },
          },

          label: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IssueLabel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteIssueLabel(
    @common.Param() params: IssueLabelWhereUniqueInput
  ): Promise<IssueLabel | null> {
    try {
      return await this.service.deleteIssueLabel({
        where: params,
        select: {
          createdAt: true,
          id: true,

          issue: {
            select: {
              id: true,
            },
          },

          label: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
